---
title: "Pituitary Inflammation: Preprocessing"
author: "Ruiyu Ray Wang"
date: "`r Sys.Date()`"
output: html_document
knit: (function(input_file, encoding){
  out_dir <- '../docs';
  rmarkdown::render(input_file,
    encoding=encoding,
    output_file=file.path(dirname(input_file), out_dir, 'preprocesssing.html'))})
---

# Initialization

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(Seurat)
  library(tidyverse)
  library(scater)
})
```

```{r}
WRITE_CACHE = FALSE
READ_CACHE = !WRITE_CACHE
```


## Load data

```{r}
data_long <- read.table(file = '../data/processed/Pituitary_counts_all.tsv.gz', sep = "\t", header = TRUE)
data <- pivot_wider(data_long, names_from = "cell", values_from = "count", values_fill = 0)
ens_id <- data %>% pull("gene")
data <- data %>% column_to_rownames(var = "gene") %>% as.data.frame()
```

```{r}
## Create Seurat Object
cells <- CreateSeuratObject(data, project = "PIT_INFL")

cells[["barcode"]] <- str_split(string = rownames(cells[[]]), pattern = "_", simplify = TRUE)[,1]
cells[["library"]] <- str_split(string = rownames(cells[[]]), pattern = "_", simplify = TRUE)[,2]
```

Convert to SCE object for `scater` QC.
```{r}
cells <- DietSeurat(cells)
cells.sce <- as.SingleCellExperiment(cells)
cells.sce <- logNormCounts(cells.sce)
dim(cells.sce)
```

## Parse metadata

Attach sample metadata to the `colData` slot of SCE object.
```{r}
meta <- read.csv('../miscs/metadata.csv')
meta <- inner_join(x = colData(cells.sce) |> as.data.frame() |> rownames_to_column("cell_id"), y = meta, by = "library") |> 
  column_to_rownames("cell_id")
meta[["treat_dose_duration"]] <- paste(meta$treat, paste(meta$dose, meta$duration, sep = " "), sep = " ")
meta <- meta |> mutate(stim = recode(treat_dose_duration, 
                                     'Saline 0g 6h' = 'Ctrl', 'Saline 0g 3h' = 'Ctrl', 'LPS 500ug 3w' = 'LPS >3w',
                                     'LPS 500ug 4w' = 'LPS >3w', 'LPS 500ug 5w' = 'LPS >3w', 'LPS 1mg 3w' = 'LPS >3w',
                                     'Poly(i:c) 20mg 3w' = 'Poly(i:c) >3w', 'Poly(i:c) 20mg 5w' = 'Poly(i:c) >3w', 'Poly(i:c) 20mg 8w' = 'Poly(i:c) >3w'))

colData(cells.sce) <- DataFrame(meta)
```

## Quality Control

### Cell level QC

```{r}
per.cell <- perCellQCMetrics(cells.sce,
                             subsets = list(Mito = grep("^mt-", rownames(cells.sce)),
                                            Ribo = grep("\\bRp[sl]\\d+[^k]*\\b", rownames(cells.sce))))
colData(cells.sce) <- cbind(colData(cells.sce), per.cell)

qc.stats <- quickPerCellQC(per.cell, percent_subsets = c("subsets_Mito_percent","subsets_Ribo_percent"))
colData(cells.sce) <- cbind(colData(cells.sce), qc.stats)
colSums(as.matrix(qc.stats))
cells.filtered <- cells.sce[,!qc.stats$discard]
```

### Feature level QC

```{r}
keep_feature <- nexprs(cells.filtered, byrow=TRUE) > 0
## Remove mitochondrial and ribosomal genes which does not contribute to analysis (i.e. cell clustering)
keep_feature[grep("\\bRp[sl]\\d+[^k]*\\b", rownames(cells.sce))] <- FALSE
keep_feature[grep("mt-", rownames(cells.sce))] <- FALSE
cells.filtered <- cells.filtered[keep_feature,]
```

```{r}
cells.new <- as.Seurat(cells.filtered)
cells.new[["ident"]] <- NULL
```

## Save data objects

```{r}
if(WRITE_CACHE){
  saveRDS(cells.sce, file = "../data/processed/cells.sce.rds")  ## Raw SCE object for QC stat plots
  saveRDS(cells.filtered, file = "../data/processed/cells.filtered.sce.rds")  ## SCE object for cellassign
  SeuratDisk::SaveH5Seurat(object = cells.new, filename = "../data/processed/cells_pre.h5Seurat", overwrite = T)  ## Seurat object
}
```

## Reproducing Plots

```{r}
if(READ_CACHE){ cells.sce = readRDS("../data/processed/cells.sce.rds") }
```

### Supplementary Figure 1a

```{r}
as.data.frame(colData(cells.sce)[,c("nCount_RNA","nFeature_RNA","discard")]) %>%
  ggplot(mapping = aes(x=nCount_RNA, y=nFeature_RNA)) +
  geom_point(aes(color = discard), size = .8) +
  scale_color_manual(values = c("#1F78B4","#E31A1C"), labels = c("Kept","Removed"), name = "") +
  scale_x_continuous(expand = c(0.15,0.1)) +
  xlab("UMI counts") +
  ylab("Number of Genes Recovered") +
  theme_classic() +
  theme(
    axis.text = element_text(size = 16),
    axis.title = element_text(size = 21),
    legend.title = element_blank(),
    legend.box.background = element_blank(),
    legend.position = c(.95, .05),
    legend.justification = c("right", "bottom"),
    legend.text = element_text(size = 16),
    legend.margin = margin(1, 5, 5, 5)
    )
```

### Supplementary Figure 1b

```{r}
as.data.frame(colData(cells.sce)[,c("subsets_Mito_percent","stim","high_subsets_Mito_percent")]) |>
  ggplot(mapping = aes(x=stim, y=subsets_Mito_percent)) +
  geom_violin() +
  geom_jitter(mapping = aes(color = high_subsets_Mito_percent), size = 0.3, height = 0, width = .1) +
  scale_color_manual(values = c("#1F78B4","#E31A1C")) +
  theme_linedraw() +
  xlab("Experimental Condition") +
  ylab("Percent Mitochondrial (%)") +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)
  )
```

### Supplementary Figure 1c

```{r}
as.data.frame(colData(cells.sce)[,c("subsets_Ribo_percent","stim","high_subsets_Ribo_percent")]) |>
  ggplot(mapping = aes(x=stim, y=subsets_Ribo_percent)) +
  geom_violin() +
  geom_jitter(mapping = aes(color = high_subsets_Ribo_percent), size = 0.3, height = 0, width = .1) +
  scale_color_manual(values = c("#1F78B4","#E31A1C")) +
  xlab("Experimental Condition") +
  ylab("Percent Ribosomal (%)") +
  theme_linedraw() +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)
  )
```

### Session info

```{r}
sessionInfo()
```
